"use client"
import { ConnectButton } from '@rainbow-me/rainbowkit';
import { Flex, Text } from '@chakra-ui/react'
import Link from 'next/link'
import Head from 'next/head'
import AddNFTsButton from '../Buttons/AddSFTsButton';

export const Header = () => {
    return (
        <>
            <Head>
                <title>Actiplace</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Flex h="15vh" p="1rem" justifyContent="space-between" alignItems="center" paddingLeft="1rem" paddingRight="1rem" backgroundColor="#022E69" textColor="white">
                <Flex>
                    <Text>Acti</Text>
                    <Text textColor="#FF914D">Place</Text>
                </Flex>
                
                
                <Link href="/">Accueil</Link>
                <Link href="/activities">Activités</Link>
                <Link href="/community">Communauté</Link>
                <Link href="/contact">Contact</Link>                
                
                <ConnectButton 
                accountStatus={{
                    smallScreen: 'avatar',
                    largeScreen: 'full',
                  }}/>
            </Flex>
        </>
    )
}